### ISSUE TITLE
How to Display or know it is working?

### ISSUE THREAD

**Issue by mcsarge** [jbakuwel/venus-midnite#1]
Can you describe how to know the integration is working? I see no log files and I do not know how to access the data from the driver to display it on the screen. I am a newbie, but I am at a loss on this.

When I do a "ps | grep battery" I see a "supervise battery" process listed, same for charger.

**Comment by mcsarge** [comment]
OK, well I figured out a couple of things. YOu want to extract the zip file of code in the Cerbo so it preserves the executable settings. Also, I found an error in the Battery code, if you set the MQTT to False, it always sets the battery to disconnected. I do not think that is right. I will fork a branch and make the changes.

**Comment by mcsarge** [comment]
I can run battey.sh fine and see the output of the log, but when I run it with rcS.local I do not see the logs, can you tell me how I can see the log files?

**Comment by jbakuwel** [comment]
@mcsarge Thanks for the bug report, that should be fixed. Re logging, I think that needs a bit of TLC :-) suggestions (or better: PR) welcome.

**Comment by mcsarge** [comment]
I figured out the logging - the "run" in the log directory of "service" needs to be executable.

**Comment by mcsarge** [comment]
When I ran Battery, I was getting lockups where they data no longer flowed. While I was trying to fix that but before I figured out the log issue, I added a watchdog. Do you want me to leave that in when I check my stuff in? I can add it to the charge code too.

**Comment by jbakuwel** [comment]
@mcsarge Great, thanks! I've updated the repo.
