### ISSUE TITLE
Lockups

### ISSUE THREAD

**Issue by jbakuwel** [jbakuwel/venus-midnite#2]
At times the software seems to lock up.

**Comment by jbakuwel** [comment]
@mcsarge wrote:

When I ran Battery, I was getting lockups where they data no longer flowed. While I was trying to fix that but before I figured out the log issue, I added a watchdog. Do you want me to leave that in when I check my stuff in? I can add it to the charge code too.

**Comment by jbakuwel** [comment]
@mcsarge Yes, please if you found an issue and a fix, please create a PR. If you're not familiar with the process (and it's a small fix), feel free to post it here and I'll add it to the code.

**Comment by mcsarge** [comment]
I will add the watchdog to the charger code as well and then post a PR. Might be a day or two - have the real job to do :-)

**Comment by jbakuwel** [comment]
I haven't experienced any lock up issues with v2, closing this issue.
